directories:
  output: release
  buildResources: resources
productName: WhaleEx
appId: org.develar.whaleex
compression: normal
files:
  - filter:
      - app/dist/
      - app/app.html
      - app/main.prod.js
      - app/main.prod.js.map
      - package.json
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
linux:
  target:
    - deb
    - rpm
    - snap
    - AppImage
  category: Development
publish:
  - provider: generic
    url: 'https:///${name}/${os}/${arch}/'
  - provider: custom
    providerName: alioss
    path: '/${name}/${os}/${arch}/'
    bucket: whaleex-electron-test
    region: oss-cn-shanghai
    accessKeyId: LTAIQ3betR33lolr
    accessKeySecret: 5uBLJrIb9tdtIlGbwpNYNh2FPAkATh
    resumable: true
    verbose: true
electronVersion: 3.0.10
